/*
 * esbuild 构建配置
 *
 * 为什么用 esbuild？Obsidian 官方推荐，打包速度快（比 tsc 快 10x+）。
 * 开发时用 watch 模式，改代码自动重新打包；生产用 production 参数做 tree-shaking。
 *
 * external 列表中的模块（obsidian、codemirror 等）由 Obsidian 宿主环境提供，
 * 打包时排除掉，不放进 main.js，否则会重复打包导致冲突。
 */

import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

// esbuild 会把所有代码打包成一个文件，加上这段 banner 标记生成来源
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: src/main.ts
*/`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],   // 入口文件：只从 main.ts 开始打包
  bundle: true,                   // 打包所有 import 的依赖
  external: [                     // 这些模块不打包，由运行时提供
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@codemirror/stream-parser",
    ...builtins,                  // Node.js 内置模块（path, fs 等）
  ],
  format: "cjs",                  // Obsidian 使用 CommonJS 模块格式
  target: "es2018",               // 目标 ES 版本，兼顾兼容性
  logLevel: "info",
  sourcemap: prod ? false : "inline",  // 开发时内联 sourcemap 方便调试
  treeShaking: true,                    // 移除未使用的代码，减小体积
  outfile: "main.js",                   // 输出文件
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  // 开发模式：监听文件变化，自动重新打包
  await context.watch();
}
